In [ ]:
#standard imports
import pandas as pd
import numpy as np
from google.colab import drive
from sklearn.linear_model import LinearRegression

In [ ]:
#mounting from google drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#reading csv
raw_census = pd.read_csv('/content/drive/Shareddrives/Rice Datathon 2023/Copy of sc-est2019-agesex-civ.csv')
raw_census = raw_census[raw_census['NAME']!='United States']
raw_census = raw_census[(raw_census['SEX'] == 2) & (raw_census['AGE'] >= 50)]
raw_census = raw_census[['NAME', 'POPEST2010_CIV', 'POPEST2011_CIV', 'POPEST2012_CIV', 'POPEST2013_CIV', 'POPEST2014_CIV',
                          'POPEST2015_CIV', 'POPEST2016_CIV', 'POPEST2017_CIV', 'POPEST2018_CIV', 'POPEST2019_CIV']]
                          
raw_census.head()

,NAME,POPEST2010_CIV,POPEST2011_CIV,POPEST2012_CIV,POPEST2013_CIV,POPEST2014_CIV,POPEST2015_CIV,POPEST2016_CIV,POPEST2017_CIV,POPEST2018_CIV,POPEST2019_CIV
485,Alabama,36351,36060,35534,35043,34960,34245,31850,30678,30586,31253
486,Alabama,35727,36375,35928,35554,34991,34954,34236,31818,30657,30659
487,Alabama,35945,35654,36384,35829,35470,34976,34913,34186,31788,30720
488,Alabama,36070,35828,35440,36311,35705,35269,34734,34794,34042,31675
489,Alabama,34862,35949,35644,35302,36238,35565,35201,34678,34779,34052

In [ ]:
# Iterate through each column in the DataFrame (excluding the first column)
for col in raw_census.columns[1:]:
    # Extract characters 7 through 10 of the column name
    year = col[6:10]
    # Rename the column
    raw_census = raw_census.rename(columns={col: year})
    
raw_census

,NAME,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
485,Alabama,36351,36060,35534,35043,34960,34245,31850,30678,30586,31253
486,Alabama,35727,36375,35928,35554,34991,34954,34236,31818,30657,30659
487,Alabama,35945,35654,36384,35829,35470,34976,34913,34186,31788,30720
488,Alabama,36070,35828,35440,36311,35705,35269,34734,34794,34042,31675
489,Alabama,34862,35949,35644,35302,36238,35565,35201,34678,34779,34052
...,...,...,...,...,...,...,...,...,...,...,...
13567,Wyoming,1103,1107,1084,1106,1105,1037,1091,1126,1110,1166
13568,Wyoming,936,1028,1035,1002,1030,1031,954,1024,1047,1036
13569,Wyoming,883,880,1011,988,945,973,974,916,984,1006
13570,Wyoming,5646,5731,5849,6042,6250,6371,6543,6741,6801,6863
13571,Wyoming,276212,277554,281563,284372,284645,285849,285299,283137,282798,283502

In [ ]:
# create a new dataframe with the state name and a column for each year
raw_census = raw_census.groupby('NAME').sum().reset_index()

# Print the DataFrame to confirm the new column has been added
raw_census

,NAME,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Alabama,3328501,3352897,3376771,3398474,3420078,3439010,3457707,3475317,3493467,3513472
1,Alaska,435415,442631,448738,452475,453348,455520,458899,460232,459475,458843
2,Arizona,4300778,4363773,4436211,4506576,4587763,4672111,4762600,4848905,4939791,5036634
3,Arkansas,2009731,2027599,2040739,2051961,2063639,2075169,2086590,2097064,2106867,2116760
4,California,24572532,24894958,25200318,25508159,25821666,26111619,26341691,26526313,26662466,26770484
5,Colorado,3315174,3377772,3437313,3498277,3558405,3626734,3686187,3735950,3791933,3841833
6,Connecticut,2508269,2525302,2539784,2550232,2560080,2564520,2566919,2569539,2573884,2574944
7,Delaware,630267,638902,647279,656979,666915,676448,685783,694827,703770,712432
8,District of Columbia,413848,422747,432581,441839,449162,458115,464176,469548,473440,476101
9,Florida,13376967,13571211,13797179,14021240,14289893,14591556,14917756,15204799,15445020,15660155
10,Georgia,6474015,6562624,6659545,6743936,6840895,6946415,7054900,7151477,7242814,7340494
11,Hawaii,922494,934971,946725,956933,963273,969725,975971,978190,979925,980505
12,Idaho,1033382,1047028,1059249,1073596,1089774,1106144,1128728,1153787,1177370,1204569
13,Illinois,8716261,8771492,8816354,8854107,8880373,8889395,8885215,8877625,8860716,8846199
14,Indiana,4418939,4453258,4481425,4514666,4544754,4564874,4589931,4613229,4642327,4672296
15,Iowa,2099861,2114558,2126231,2140291,2153543,2162461,2170392,2177598,2183960,2190040
16,Kansas,1924823,1938129,1951997,1961186,1969608,1977863,1982007,1983549,1987290,1992220
17,Kentucky,2981070,3006619,3026471,3047640,3066679,3083111,3098577,3112141,3124772,3135278
18,Louisiana,3086458,3120138,3148665,3174381,3197529,3221521,3240831,3247533,3251299,3254513
19,Maine,952178,957679,962611,967161,973624,975838,980855,985794,991586,997531
20,Maryland,3993395,4043586,4091579,4132542,4173702,4207902,4231865,4257668,4278535,4297127
21,Massachusetts,4595154,4642999,4690772,4740920,4790209,4827008,4858181,4891943,4918794,4935859
22,Michigan,6845525,6880616,6914902,6948891,6981637,6999086,7023572,7049498,7070006,7086086
23,Minnesota,3583336,3622759,3658103,3696173,3731913,3760546,3793134,3825762,3856607,3884493
24,Mississippi,2036252,2049205,2059825,2069316,2079420,2086548,2092088,2096924,2098730,2102384
25,Missouri,4139249,4165216,4191265,4214726,4238728,4259042,4276539,4295629,4312119,4329784
26,Montana,681351,688513,694735,702483,709233,715476,723014,731161,737803,744258
27,Nebraska,1234925,1245551,1256651,1265972,1276464,1284814,1293915,1300388,1307408,1313886
28,Nevada,1761334,1779355,1809521,1840906,1878193,1919243,1958879,1999840,2043582,2085293
29,New Hampshire,914521,922863,931724,938309,947344,952789,960204,967909,973744,981415
30,New Jersey,6107265,6148847,6184645,6215445,6244187,6268025,6285403,6307155,6318685,6327306
31,New Mexico,1402999,1419006,1427834,1435854,1439372,1444741,1449984,1454366,1459289,1466084
32,New York,13499264,13607675,13697349,13775916,13843868,13889221,13909534,13914098,13905737,13885494
33,North Carolina,6558299,6649474,6741763,6835080,6927917,7020263,7123695,7223744,7323483,7422035
34,North Dakota,452669,459158,467530,477939,485496,493905,494832,496217,498567,501147
35,Ohio,8048464,8082574,8109503,8146628,8185186,8210739,8233114,8259173,8280901,8300670
36,Oklahoma,2545938,2571208,2595345,2621704,2643152,2666561,2681149,2687876,2697241,2711637
37,Oregon,2639896,2672502,2699105,2723709,2756797,2796014,2846164,2884293,2914728,2945096
38,Pennsylvania,8994921,9043974,9080820,9106890,9140632,9157173,9171590,9189187,9207549,9219775
39,Rhode Island,744066,746110,749310,751972,754381,755881,757722,758933,761534,763560
40,South Carolina,3215853,3257611,3304185,3350919,3408004,3468345,3528147,3584322,3641846,3701627
41,South Dakota,551289,556391,563592,570543,576095,580142,585709,591681,596606,601291
42,Tennessee,4394369,4441323,4490936,4533536,4579222,4625673,4672386,4720327,4770461,4820826
43,Texas,16379980,16698787,17027711,17330123,17680800,18037051,18354710,18634508,18894179,19175949
44,Utah,1717853,1747543,1775612,1806927,1835660,1866143,1904625,1942678,1978437,2015225
45,Vermont,440922,443867,445489,447396,448649,449902,449837,451328,452317,452780
46,Virginia,5425759,5497584,5572639,5636387,5696276,5749337,5797128,5847025,5888128,5926463
47,Washington,4519734,4588336,4650718,4708684,4777494,4857332,4945053,5031479,5102308,5169202
48,West Virginia,1315012,1319018,1321450,1321966,1322222,1318906,1313458,1305485,1298770,1292423
49,Wisconsin,3879512,3908239,3934886,3961652,3985797,4003250,4021029,4041446,4060521,4079289
50,Wyoming,371627,375145,381449,386237,387273,389304,389287,387604,388026,389762

In [ ]:
# Load your dataframe
df = raw_census

# Create a new column that calculates the population change over the years
# df['population_change'] = df.iloc[:,1:].sum(axis=1) - df.iloc[:,1:].sum(axis=1).min()

# df.head()


# # Sort the states by population change in descending order
# df = df.sort_values(by='population_change', ascending=False)

# # Select the top n states with the most population change
# n = 10 # or any number of states you want to consider
# df_top_states = df.head(n)

# Create a new dataframe with the population estimates for the top states

if 'Rate' not in df:
  df.insert(11, "Rate", 0)

In [ ]:
# Create a new dataframe with the state names


# Create a linear regression object
years = np.array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019])

i = 0

# Fit the model using the population estimates
for row in df.iterrows():
  reg = LinearRegression().set_params(fit_intercept=True)
  #curr = np.array(row[1:][0][1:] / row[1:][0][1]) # Divide each by 2010
  curr = np.array(row[1:][0][1:11])
  #print(curr)
  reg = reg.fit(years.reshape(-1, 1), curr)

  # Print the coefficients of the linear regression
  
  #print(reg.coef_, reg.intercept_)

  df.iloc[i, 11] = (reg.coef_*2024 + reg.intercept_ - row[1:][0][-2]) / row[1:][0][-2]
  i += 1
df = df.sort_values(by=['Rate'], ascending=False)

df

,NAME,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,Rate
8,District of Columbia,413848,422747,432581,441839,449162,458115,464176,469548,473440,476101,0.087712
9,Florida,13376967,13571211,13797179,14021240,14289893,14591556,14917756,15204799,15445020,15660155,0.085770
43,Texas,16379980,16698787,17027711,17330123,17680800,18037051,18354710,18634508,18894179,19175949,0.085477
28,Nevada,1761334,1779355,1809521,1840906,1878193,1919243,1958879,1999840,2043582,2085293,0.083543
5,Colorado,3315174,3377772,3437313,3498277,3558405,3626734,3686187,3735950,3791933,3841833,0.079991
44,Utah,1717853,1747543,1775612,1806927,1835660,1866143,1904625,1942678,1978437,2015225,0.078264
2,Arizona,4300778,4363773,4436211,4506576,4587763,4672111,4762600,4848905,4939791,5036634,0.077477
40,South Carolina,3215853,3257611,3304185,3350919,3408004,3468345,3528147,3584322,3641846,3701627,0.071798
47,Washington,4519734,4588336,4650718,4708684,4777494,4857332,4945053,5031479,5102308,5169202,0.070525
34,North Dakota,452669,459158,467530,477939,485496,493905,494832,496217,498567,501147,0.068369
12,Idaho,1033382,1047028,1059249,1073596,1089774,1106144,1128728,1153787,1177370,1204569,0.067835
10,Georgia,6474015,6562624,6659545,6743936,6840895,6946415,7054900,7151477,7242814,7340494,0.066174
7,Delaware,630267,638902,647279,656979,666915,676448,685783,694827,703770,712432,0.065775
33,North Carolina,6558299,6649474,6741763,6835080,6927917,7020263,7123695,7223744,7323483,7422035,0.063821
37,Oregon,2639896,2672502,2699105,2723709,2756797,2796014,2846164,2884293,2914728,2945096,0.059499
4,California,24572532,24894958,25200318,25508159,25821666,26111619,26341691,26526313,26662466,26770484,0.054696
46,Virginia,5425759,5497584,5572639,5636387,5696276,5749337,5797128,5847025,5888128,5926463,0.051274
41,South Dakota,551289,556391,563592,570543,576095,580142,585709,591681,596606,601291,0.048395
42,Tennessee,4394369,4441323,4490936,4533536,4579222,4625673,4672386,4720327,4770461,4820826,0.047795
26,Montana,681351,688513,694735,702483,709233,715476,723014,731161,737803,744258,0.047563
20,Maryland,3993395,4043586,4091579,4132542,4173702,4207902,4231865,4257668,4278535,4297127,0.044840
21,Massachusetts,4595154,4642999,4690772,4740920,4790209,4827008,4858181,4891943,4918794,4935859,0.044837
23,Minnesota,3583336,3622759,3658103,3696173,3731913,3760546,3793134,3825762,3856607,3884493,0.044730
11,Hawaii,922494,934971,946725,956933,963273,969725,975971,978190,979925,980505,0.042083
36,Oklahoma,2545938,2571208,2595345,2621704,2643152,2666561,2681149,2687876,2697241,2711637,0.038890
29,New Hampshire,914521,922863,931724,938309,947344,952789,960204,967909,973744,981415,0.038057
1,Alaska,435415,442631,448738,452475,453348,455520,458899,460232,459475,458843,0.037457
18,Louisiana,3086458,3120138,3148665,3174381,3197529,3221521,3240831,3247533,3251299,3254513,0.037191
27,Nebraska,1234925,1245551,1256651,1265972,1276464,1284814,1293915,1300388,1307408,1313886,0.036423
50,Wyoming,371627,375145,381449,386237,387273,389304,389287,387604,388026,389762,0.030310
17,Kentucky,2981070,3006619,3026471,3047640,3066679,3083111,3098577,3112141,3124772,3135278,0.030266
0,Alabama,3328501,3352897,3376771,3398474,3420078,3439010,3457707,3475317,3493467,3513472,0.029683
14,Indiana,4418939,4453258,4481425,4514666,4544754,4564874,4589931,4613229,4642327,4672296,0.029292
3,Arkansas,2009731,2027599,2040739,2051961,2063639,2075169,2086590,2097064,2106867,2116760,0.028874
49,Wisconsin,3879512,3908239,3934886,3961652,3985797,4003250,4021029,4041446,4060521,4079289,0.028217
15,Iowa,2099861,2114558,2126231,2140291,2153543,2162461,2170392,2177598,2183960,2190040,0.026052
25,Missouri,4139249,4165216,4191265,4214726,4238728,4259042,4276539,4295629,4312119,4329784,0.025931
19,Maine,952178,957679,962611,967161,973624,975838,980855,985794,991586,997531,0.023346
30,New Jersey,6107265,6148847,6184645,6215445,6244187,6268025,6285403,6307155,6318685,6327306,0.022851
32,New York,13499264,13607675,13697349,13775916,13843868,13889221,13909534,13914098,13905737,13885494,0.022734
31,New Mexico,1402999,1419006,1427834,1435854,1439372,1444741,1449984,1454366,1459289,1466084,0.022633
16,Kansas,1924823,1938129,1951997,1961186,1969608,1977863,1982007,1983549,1987290,1992220,0.021353
24,Mississippi,2036252,2049205,2059825,2069316,2079420,2086548,2092088,2096924,2098730,2102384,0.020899
22,Michigan,6845525,6880616,6914902,6948891,6981637,6999086,7023572,7049498,7070006,7086086,0.020820
35,Ohio,8048464,8082574,8109503,8146628,8185186,8210739,8233114,8259173,8280901,8300670,0.018690
6,Connecticut,2508269,2525302,2539784,2550232,2560080,2564520,2566919,2569539,2573884,2574944,0.017180
45,Vermont,440922,443867,445489,447396,448649,449902,449837,451328,452317,452780,0.015888
38,Pennsylvania,8994921,9043974,9080820,9106890,9140632,9157173,9171590,9189187,9207549,9219775,0.014886
39,Rhode Island,744066,746110,749310,751972,754381,755881,757722,758933,761534,763560,0.014347
13,Illinois,8716261,8771492,8816354,8854107,8880373,8889395,8885215,8877625,8860716,8846199,0.013610
48,West Virginia,1315012,1319018,1321450,1321966,1322222,1318906,1313458,1305485,1298770,1292423,-0.004390

In [ ]:
# Sort states by highest population rate increase
# df = df.sort_values(by=['Rate'], ascending=False)
# df

In [ ]:


#Calculating women >= 50 in each state / number of certified facilities per state
facilities_per_state = pd.read_csv('/content/drive/Shareddrives/Rice Datathon 2023/facilities_per_state.csv')


# if 'Pop/Fac' not in pop_per_facility:
#   pop_per_facility.insert(1, 'Pop/Fac', 0)

# for i in pop_per_facility.iterrows():
#   pop_per_facility.iloc[i,'Pop/Fac'] = df.iloc[i,10] / facilities_per_state.iloc[i,2]
# pop_per_facility

   State
0     AK
1     AL
2     AR
3     AZ
4     CA
5     CO
6     CT
7     DC
8     DE
9     FL
10    GA
11    HI
12    IA
13    ID
14    IL
15    IN
16    KS
17    KY
18    LA
19    MA
20    MD
21    ME
22    MI
23    MN
24    MO
25    MS
26    MT
27    NC
28    ND
29    NE
30    NH
31    NJ
32    NM
33    NV
34    NY
35    OH
36    OK
37    OR
38    PA
39    RI
40    SC
41    SD
42    TN
43    TX
44    UT
45    VA
46    VT
47    WA
48    WI
49    WV
50    WY

In [ ]:
# Change the state name from complete to abbreviation
df["NAME"] = df["NAME"].replace({"Alabama":"AL", "Alaska":"AK", "Arizona":"AZ", "Arkansas":"AR", "California":"CA",
                                  "Colorado":"CO", "Connecticut":"CT", "Delaware":"DE", "District of Columbia":"DC", "Florida":"FL", "Georgia":"GA",
                                  "Hawaii":"HI", "Idaho":"ID", "Illinois":"IL", "Indiana":"IN", "Iowa":"IA", "Kansas":"KS",
                                  "Kentucky":"KY", "Louisiana":"LA", "Maine":"ME", "Maryland":"MD", "Massachusetts":"MA",
                                  "Michigan":"MI", "Minnesota":"MN", "Mississippi":"MS", "Missouri":"MO", "Montana":"MT",
                                  "Nebraska":"NE", "Nevada":"NV", "New Hampshire":"NH", "New Jersey":"NJ", "New Mexico":"NM",
                                  "New York":"NY", "North Carolina":"NC", "North Dakota":"ND", "Ohio":"OH", "Oklahoma":"OK",
                                  "Oregon":"OR", "Pennsylvania":"PA", "Rhode Island":"RI", "South Carolina":"SC", 
                                  "South Dakota":"SD", "Tennessee":"TN", "Texas":"TX", "Utah":"UT", "Vermont":"VT",
                                  "Virginia":"VA", "Washington":"WA", "West Virginia":"WV", "Wisconsin":"WI", "Wyoming":"WY"})
pop_plus_fac = df.merge(facilities_per_state, how="inner", left_on="NAME", right_on="State")
pop_plus_fac

,NAME,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,Rate,Unnamed: 0,State,City
0,DC,413848,422747,432581,441839,449162,458115,464176,469548,473440,476101,0.087712,7,DC,15
1,FL,13376967,13571211,13797179,14021240,14289893,14591556,14917756,15204799,15445020,15660155,0.085770,9,FL,628
2,TX,16379980,16698787,17027711,17330123,17680800,18037051,18354710,18634508,18894179,19175949,0.085477,43,TX,574
3,NV,1761334,1779355,1809521,1840906,1878193,1919243,1958879,1999840,2043582,2085293,0.083543,33,NV,69
4,CO,3315174,3377772,3437313,3498277,3558405,3626734,3686187,3735950,3791933,3841833,0.079991,5,CO,138
5,UT,1717853,1747543,1775612,1806927,1835660,1866143,1904625,1942678,1978437,2015225,0.078264,44,UT,64
6,AZ,4300778,4363773,4436211,4506576,4587763,4672111,4762600,4848905,4939791,5036634,0.077477,3,AZ,171
7,SC,3215853,3257611,3304185,3350919,3408004,3468345,3528147,3584322,3641846,3701627,0.071798,40,SC,110
8,WA,4519734,4588336,4650718,4708684,4777494,4857332,4945053,5031479,5102308,5169202,0.070525,47,WA,149
9,ND,452669,459158,467530,477939,485496,493905,494832,496217,498567,501147,0.068369,28,ND,48
10,ID,1033382,1047028,1059249,1073596,1089774,1106144,1128728,1153787,1177370,1204569,0.067835,13,ID,49
11,GA,6474015,6562624,6659545,6743936,6840895,6946415,7054900,7151477,7242814,7340494,0.066174,10,GA,277
12,DE,630267,638902,647279,656979,666915,676448,685783,694827,703770,712432,0.065775,8,DE,30
13,NC,6558299,6649474,6741763,6835080,6927917,7020263,7123695,7223744,7323483,7422035,0.063821,27,NC,270
14,OR,2639896,2672502,2699105,2723709,2756797,2796014,2846164,2884293,2914728,2945096,0.059499,37,OR,108
15,CA,24572532,24894958,25200318,25508159,25821666,26111619,26341691,26526313,26662466,26770484,0.054696,4,CA,761
16,VA,5425759,5497584,5572639,5636387,5696276,5749337,5797128,5847025,5888128,5926463,0.051274,45,VA,205
17,SD,551289,556391,563592,570543,576095,580142,585709,591681,596606,601291,0.048395,41,SD,48
18,TN,4394369,4441323,4490936,4533536,4579222,4625673,4672386,4720327,4770461,4820826,0.047795,42,TN,192
19,MT,681351,688513,694735,702483,709233,715476,723014,731161,737803,744258,0.047563,26,MT,47
20,MD,3993395,4043586,4091579,4132542,4173702,4207902,4231865,4257668,4278535,4297127,0.044840,20,MD,132
21,MA,4595154,4642999,4690772,4740920,4790209,4827008,4858181,4891943,4918794,4935859,0.044837,19,MA,155
22,MN,3583336,3622759,3658103,3696173,3731913,3760546,3793134,3825762,3856607,3884493,0.044730,23,MN,210
23,HI,922494,934971,946725,956933,963273,969725,975971,978190,979925,980505,0.042083,11,HI,37
24,OK,2545938,2571208,2595345,2621704,2643152,2666561,2681149,2687876,2697241,2711637,0.038890,36,OK,116
25,NH,914521,922863,931724,938309,947344,952789,960204,967909,973744,981415,0.038057,30,NH,44
26,AK,435415,442631,448738,452475,453348,455520,458899,460232,459475,458843,0.037457,0,AK,33
27,LA,3086458,3120138,3148665,3174381,3197529,3221521,3240831,3247533,3251299,3254513,0.037191,18,LA,145
28,NE,1234925,1245551,1256651,1265972,1276464,1284814,1293915,1300388,1307408,1313886,0.036423,29,NE,93
29,WY,371627,375145,381449,386237,387273,389304,389287,387604,388026,389762,0.030310,50,WY,30
30,KY,2981070,3006619,3026471,3047640,3066679,3083111,3098577,3112141,3124772,3135278,0.030266,17,KY,144
31,AL,3328501,3352897,3376771,3398474,3420078,3439010,3457707,3475317,3493467,3513472,0.029683,1,AL,141
32,IN,4418939,4453258,4481425,4514666,4544754,4564874,4589931,4613229,4642327,4672296,0.029292,15,IN,179
33,AR,2009731,2027599,2040739,2051961,2063639,2075169,2086590,2097064,2106867,2116760,0.028874,2,AR,83
34,WI,3879512,3908239,3934886,3961652,3985797,4003250,4021029,4041446,4060521,4079289,0.028217,48,WI,215
35,IA,2099861,2114558,2126231,2140291,2153543,2162461,2170392,2177598,2183960,2190040,0.026052,12,IA,145
36,MO,4139249,4165216,4191265,4214726,4238728,4259042,4276539,4295629,4312119,4329784,0.025931,24,MO,159
37,ME,952178,957679,962611,967161,973624,975838,980855,985794,991586,997531,0.023346,21,ME,48
38,NJ,6107265,6148847,6184645,6215445,6244187,6268025,6285403,6307155,6318685,6327306,0.022851,31,NJ,247
39,NY,13499264,13607675,13697349,13775916,13843868,13889221,13909534,13914098,13905737,13885494,0.022734,34,NY,550
40,NM,1402999,1419006,1427834,1435854,1439372,1444741,1449984,1454366,1459289,1466084,0.022633,32,NM,46
41,KS,1924823,1938129,1951997,1961186,1969608,1977863,1982007,1983549,1987290,1992220,0.021353,16,KS,109
42,MS,2036252,2049205,2059825,2069316,2079420,2086548,2092088,2096924,2098730,2102384,0.020899,25,MS,99
43,MI,6845525,6880616,6914902,6948891,6981637,6999086,7023572,7049498,7070006,7086086,0.020820,22,MI,271
44,OH,8048464,8082574,8109503,8146628,8185186,8210739,8233114,8259173,8280901,8300670,0.018690,35,OH,333
45,CT,2508269,2525302,2539784,2550232,2560080,2564520,2566919,2569539,2573884,2574944,0.017180,6,CT,114
46,VT,440922,443867,445489,447396,448649,449902,449837,451328,452317,452780,0.015888,46,VT,15
47,PA,8994921,9043974,9080820,9106890,9140632,9157173,9171590,9189187,9207549,9219775,0.014886,38,PA,343
48,RI,744066,746110,749310,751972,754381,755881,757722,758933,761534,763560,0.014347,39,RI,34
49,IL,8716261,8771492,8816354,8854107,8880373,8889395,8885215,8877625,8860716,8846199,0.013610,14,IL,335
50,WV,1315012,1319018,1321450,1321966,1322222,1318906,1313458,1305485,1298770,1292423,-0.004390,49,WV,64

In [ ]:
pop_plus_fac['Pop/Fac'] = pop_plus_fac['2019'] / pop_plus_fac['City']
pop_per_facility = pop_plus_fac[['State','Pop/Fac']]
#pop_per_facility
print(pop_per_facility['Pop/Fac'].max())
print(pop_per_facility['Pop/Fac'].min())
pop_per_facility.to_csv('/content/drive/Shareddrives/Rice Datathon 2023/women_per_facility.csv', index=False)

35178.03416557162
10440.5625

In [ ]:

percent_increase = df[['NAME', 'Rate']]
percent_increase
percent_increase.to_csv('/content/drive/Shareddrives/Rice Datathon 2023/percent_increase.csv', index = False)